RobertCraigie/prisma-client-py

docs/reference/limitations.md, src/prisma/generator/templates/_header.py.jinja, src/prisma/generator/templates/actions.py.jinja, src/prisma/generator/templates/client.py.jinja, src/prisma/generator/templates/models.py.jinja, tests/integrations/recursive-types/test.sh, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr, tests/test_models.py, typesafety/mypy/test_mypy.yml
We have to refactor this as mypy takes a massive performance hit otherwise.
closes #100
=> refactor(actions): only generate generic actions with recursive types

docs/reference/operations.md, docs/src_examples/operations.schema.prisma, src/prisma/generator/models.py, src/prisma/generator/templates/builder.py.jinja, src/prisma/generator/templates/fields.py.jinja, src/prisma/generator/templates/models.py.jinja, src/prisma/generator/templates/partials.py.jinja, src/prisma/generator/templates/types.py.jinja, tests/data/schema.prisma, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr, tests/test_generation/exhaustive/async.schema.prisma, tests/test_generation/exhaustive/sync.schema.prisma, tests/test_generation/test_partial_types.py, tests/test_generation/test_validation.py, tests/test_types/test_bytes.py, typesafety/pyright/schema.prisma, typesafety/pyright/types/bytes.py
=> feat(client): add support for the Bytes type

src/prisma/generator/templates/models.py.jinja, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr, tests/test_types/test_bytes.py
=> fix(models): specify json encoder for Base64 fields

src/prisma/_constants.py, src/prisma/generator/models.py, src/prisma/generator/templates/builder.py.jinja, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr, tests/test_generation/test_validation.py
=> feat(generation): validate field names don't shadow query builder aliases

src/prisma/_constants.py, src/prisma/errors.py, src/prisma/generator/generator.py, src/prisma/generator/models.py, src/prisma/generator/templates/fields.py.jinja, src/prisma/generator/templates/models.py.jinja, src/prisma/generator/templates/partials.py.jinja, src/prisma/generator/templates/types.py.jinja, tests/integrations/postgresql/schema.prisma, tests/integrations/postgresql/tests/test_arrays.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr, tests/test_generation/exhaustive/async.schema.prisma, tests/test_generation/exhaustive/sync.schema.prisma, tests/test_generation/test_assumptions.py, tests/test_generation/test_partial_types.py, typesafety/pyright/schema.prisma, typesafety/pyright/types/lists.py
=> feat(client): add support for scalar list fields

src/prisma/generator/templates/actions.py.jinja, tests/test_count.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr
=> refactor(actions/count): deprecate order argument

codecov.yml, src/prisma/generator/models.py, src/prisma/generator/templates/actions.py.jinja, src/prisma/generator/utils.py, tests/test_count.py, tests/test_docs/test_docstrings.py, tests/test_find_many.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr, tests/test_generation/test_generator.py
=> feat(actions): add docstrings to all methods

.pylintrc, src/prisma/generator/errors.py, src/prisma/generator/models.py, src/prisma/generator/schema.py, src/prisma/generator/templates/actions.py.jinja, src/prisma/generator/templates/types.py.jinja, tests/__snapshots__/test_builder.ambr, tests/data/schema.prisma, tests/integrations/postgresql/schema.prisma, tests/integrations/postgresql/tests/test_uniques.py, tests/test_builder.py, tests/test_find_unique.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr, tests/test_generation/exhaustive/async.schema.prisma, tests/test_generation/exhaustive/sync.schema.prisma, tests/test_generation/test_assumptions.py, tests/test_generation/test_validation.py, tests/test_raw_queries.py, tests/utils.py, typesafety/mypy/test_mypy.yml, typesafety/pyright/find_unique.py, typesafety/pyright/schema.prisma, typesafety/pyright/update.py, typesafety/pyright/upsert.py
closes #54
closes #48
This PR adds support for combined unique constraints with `@@id` and `@@unique`:
```prisma
model User {
name     String
surname String
@@unique([name, surname])
}
```
=> feat(client): add support for combined unique constraints

docs/reference/client.md, mkdocs.yml, src/prisma/generator/templates/client.py.jinja, tests/integrations/sync/tests/test_basic.py, tests/test_client.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr
=> feat(client): add support for connecting using a context manager

docs/reference/model-actions.md, src/prisma/generator/templates/client.py.jinja, tests/test_client.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr
=> feat(client): add support for automatically registering the client

src/prisma/generator/templates/builder.py.jinja, tests/integrations/postgresql/tests/test_datetime.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr
=> fix(client): limit datetime microsecond precision to 3 places

src/prisma/generator/models.py
=> chore(generator): reference node CLI in version mismatch error

src/prisma/generator/templates/client.py.jinja, tests/test_client.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr, tox.ini
=> feat(client): support setting a default connection timeout

src/prisma/_async_http.py, src/prisma/_sync_http.py, src/prisma/http_abstract.py
=> fix(http): fix blocking IO under async

.github/workflows/test.yml, .pylintrc, docs/contributing/architecture.md, src/prisma/_types.py, src/prisma/cli/cli.py, src/prisma/cli/prisma.py, src/prisma/generator/__init__.py, src/prisma/generator/generator.py, src/prisma/generator/jsonrpc.py, src/prisma/generator/models.py, tests/integrations/custom-generator/.gitignore, tests/integrations/custom-generator/1.prisma, tests/integrations/custom-generator/2.prisma, tests/integrations/custom-generator/generator.py, tests/integrations/custom-generator/pyproject.toml, tests/integrations/custom-generator/test.py, tests/integrations/custom-generator/test.sh, tests/test_generation/test_generator.py, typesafety/pyright/generators/base.py, typesafety/pyright/generators/generic.py
=> feat(generator): support custom python generators

src/prisma/cli/commands/dev.py
=> fix(cli/dev): remove unconditional auto-generated import

src/prisma/errors.py, src/prisma/generator/templates/client.py.jinja, src/prisma/generator/templates/models.py.jinja, tests/data/schema.prisma, tests/integrations/postgresql/tests/conftest.py, tests/integrations/postgresql/tests/test_models.py, tests/test_cli/test_dev.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr, tests/test_models.py, tests/test_types/test_bool.py, tox.ini
=> feat(models): warn on model subclass instead of crashing

src/prisma/generator/models.py, src/prisma/generator/templates/types.py.jinja, tests/integrations/postgresql/schema.prisma, tests/integrations/postgresql/tests/test_uniques.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr, tests/test_generation/exhaustive/async.schema.prisma, tests/test_generation/exhaustive/sync.schema.prisma
=> fix(types): correctly render enum fields within compound keys

docs/getting_started/partial-types.md, docs/reference/config.md, docs/reference/partials.md, mkdocs.yml, src/prisma/generator/templates/models.py.jinja, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr, tests/test_generation/test_partial_types.py
=> feat(partials): add support for excluding all relational fields

src/prisma/http_abstract.py, tests/test_client.py, tests/test_http.py, tests/utils.py
=> feat(http): increase default timeout to 30 seconds

src/prisma/generator/templates/types.py.jinja, tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr, typesafety/pyright/update_many.py
=> fix(types): remove relational fields from update_many mutation data

docs/reference/operations.md, src/prisma/generator/templates/actions.py.jinja, tests/test_count.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[actions.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[actions.py].raw
=> chore(actions/count): remove deprecated order argument

Makefile, docs/reference/binaries.md, mkdocs.yml, scripts/docs.py, src/prisma/binaries/binaries.py, src/prisma/binaries/binary.py, tests/test_binaries.py
=> feat(binaries/cli): support resolving from an env variable

src/prisma/generator/templates/types.py.jinja, tests/conftest.py, tests/test_actions.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[types.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[types.py].raw, typesafety/pyright/include.py
=> fix(types/include): fix incorrect relational order_by type

docs/reference/binaries.md, src/prisma/binaries/constants.py
Upgrade internal prisma binaries to v3.8.1
=> feat(prisma): upgrade to prisma@3.8.1

docs/reference/limitations.md, docs/reference/operations.md, docs/src_examples/operations.schema.prisma, src/prisma/engine/utils.py, src/prisma/errors.py, src/prisma/generator/models.py, src/prisma/generator/templates/_utils.py.jinja, src/prisma/generator/templates/actions.py.jinja, src/prisma/generator/templates/types.py.jinja, tests/__snapshots__/test_group_by.ambr, tests/data/schema.prisma, tests/test_batch.py, tests/test_find_first.py, tests/test_find_many.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[actions.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[types.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[actions.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[types.py].raw, tests/test_group_by.py, typesafety/pyright/group_by.py, typesafety/pyright/schema.prisma
=> feat(client): add group_by action

src/prisma/generator/templates/types.py.jinja, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[types.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[types.py].raw, tests/test_update.py
=> feat(client): add support for updating unique fields

src/prisma/cli/prisma.py, tests/test_cli/test_cli.py
=> feat(cli): improve studio unsupported error message

src/prisma/generator/templates/builder.py.jinja, tests/__snapshots__/test_builder.ambr, tests/data/schema.prisma, tests/test_find_first.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[builder.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[builder.py].raw, tests/test_models.py, tests/test_raw_queries.py
=> fix(builder): transform global aliases for nested lists

examples/README.md
Adds a README to the examples directory outlining the existing examples and how to contribute.
=> docs(examples): add README

src/prisma/generator/templates/models.py.jinja, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[models.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[models.py].raw, tests/test_models.py, tox.ini
=> feat(models): do not raise subclass warning with FastAPI

src/prisma/binaries/constants.py
=> feat(prisma): upgrade to prisma@3.9.1

src/prisma/generator/templates/actions.py.jinja, src/prisma/generator/templates/client.py.jinja
=> fix(mongodb): disable raw queries

src/prisma/generator/models.py, src/prisma/generator/templates/models.py.jinja, src/prisma/generator/templates/partials.py.jinja, src/prisma/generator/types.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[models.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[models.py].raw, tests/test_generation/exhaustive/async.schema.prisma, tests/test_generation/exhaustive/sync.schema.prisma
=> feat(models): add triple-slash comments to generated models

README.md, docs/index.md, docs/reference/binaries.md, src/prisma/binaries/constants.py, src/prisma/cli/commands/dev.py
=> feat(prisma): upgrade to prisma@3.11.1

src/prisma/cli/commands/dev.py
=> chore(lint): remove unused type ignore comment

src/prisma/__init__.py
=> feat(package): release v0.6.4

README.md, docs/index.md, docs/reference/binaries.md, src/prisma/binaries/constants.py
=> feat(prisma): upgrade to prisma@3.12.0

src/prisma/engine/utils.py, src/prisma/errors.py, tests/test_errors.py, tox.ini
=> feat(client): add FieldNotFoundError

typesafety/mypy/test_mypy.yml
=> chore(typesafety/mypy): fix revealed type messages

docs/contributing/contributing.md
Just a minor typo fix in contributing.md
=> chore(docs): fix typo in contributing.md

src/prisma/binaries/constants.py
=> feat(prisma): upgrade to prisma@3.13.0

README.md, docs/index.md, docs/reference/binaries.md, src/prisma/__init__.py
=> feat(package): release v0.6.5

src/prisma/generator/utils.py
=> fix(generator): move sampler iteration outside of the class

src/prisma/__init__.py
=> feat(package): release v0.6.6

src/prisma/generator/templates/client.py.jinja, tests/test_dotenv.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
=> fix(client): do not override present system env variables

src/prisma/__init__.py, src/prisma/_config.py, src/prisma/_proxy.py, src/prisma/errors.py
Abstracts our lazy loading proxy interface so that it can be used in other places as well.
=> refactor(config): make lazy loading proxy abstract

.gitignore
https://discord.com/channels/933860922039099444/933861040565932062/1011167561049702400
=> chore(project): add `.envrc` to the gitignore

src/prisma/generator/templates/fields.py.jinja, src/prisma/generator/templates/models.py.jinja, src/prisma/generator/templates/partials.py.jinja, tests/integrations/postgresql/tests/test_types.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[fields.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[models.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[fields.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[models.py].raw, tests/test_types/__snapshots__/test_compat.ambr, tests/test_types/test_bytes.py, tests/test_types/test_compat.py
=> feat(types): add support for generating OpenAPI types for Base64

src/prisma/_config.py, tests/test_config.py
=> fix(config): ensure all config options read from the environment

pipelines/test.nox.py, pipelines/utils/utils.py, setup.py
=> feat(package): add support for Python 3.11

pyproject.toml, scripts/docs.py
=> fix(scripts/docs): update script for new config structure

src/prisma/__init__.py
=> feat(package): release v0.7.0

.gitignore, src/prisma/generator/generator.py, src/prisma/generator/templates/client.py.jinja, src/prisma/generator/templates/engine/query.py.jinja, tests/test_engine.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[enginequery.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[enginequery.py].raw
=> fix(client): pass DML path to the query engine instead of the contents

src/prisma/generator/errors.py, src/prisma/generator/generator.py, src/prisma/generator/jsonrpc.py, src/prisma/generator/models.py, tests/test_generation/test_generator.py
This fixes https://github.com/prisma/prisma/issues/10270, getting us much closer to full Windows support.
=> refactor(generator): send explicit errors through JSONRPC

.github/workflows/test.yml
=> feat(ci): add mypy job

src/prisma/generator/templates/client.py.jinja, tests/test_batch.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
=> feat(client): add support for batching raw queries

databases/tests/test_find_first.py
=> fix(tests): mysql ordering

docs/reference/limitations.md
Fix typo in `Limitations` docs
=> chore(docs): fix typo

.github/workflows/test.yml, databases/_serve.py, databases/_types.py, databases/docker-compose.yml, databases/main.py, docs/contributing/contributing.md
This PR is an attempt to refactor the way database tests are defined in CI so that we can reuse a single job.
=> refactor(ci): switch to matrix for defining database tests

src/prisma/__init__.py
=> feat(package): release v0.7.1

.github/workflows/test.yml, databases/.example.env, databases/_types.py, databases/constants.py, databases/docker-compose.yml, databases/tests/utils.py
=> feat(ci): add tests for MariaDB

README.md, docs/index.md, pipelines/coverage.nox.py
=> feat(readme): link badge to coverage report

.github/workflows/test.yml, pipelines/coverage.nox.py
=> fix(ci): coverage script

.github/workflows/test.yml, README.md, databases/_types.py, databases/constants.py, databases/docker-compose.yml, databases/templates/schema.prisma.jinja2, databases/tests/arrays/test_enum.py, databases/tests/conftest.py, databases/tests/test_find_many.py, databases/tests/types/test_bigint.py, databases/tests/types/test_int.py, databases/tests/utils.py, databases/utils.py, docs/index.md
=> feat(ci): run CockroachDB tests in CI

.github/renovate.json
=> chore(deps): exclude docker-compose

README.md, docs/index.md
https://discord.com/channels/933860922039099444/1048952249205915750/1048957671325323274
=> chore(docs): add note to autocomplete GIF

README.md, docs/index.md, docs/reference/binaries.md, docs/reference/command-line.md
=> chore(docs): remove now incorrect prose

README.md, docs/index.md
Fix typo: langauge -> language.
=> docs: fix typo

README.md, docs/index.md, docs/reference/operations.md, scripts/docs.py
=> docs: update Prisma badge

src/prisma/__init__.py
=> feat(package): release v0.8.0

databases/_serve.py, databases/main.py, pipelines/lint.nox.py, pipelines/requirements/lint.txt, pyproject.toml
=> feat(ci): lint `databases` code too

README.md, docs/index.md, docs/reference/binaries.md, docs/reference/config.md, src/prisma/_config.py
=> feat(prisma): upgrade to `4.9.0`

.github/renovate.json
=> fix(ci): renovate configuration

README.md, docs/index.md, docs/reference/binaries.md, docs/reference/config.md, src/prisma/_config.py
=> feat(prisma): upgrade to v4.10.0

README.md, docs/index.md, docs/reference/binaries.md, docs/reference/config.md, src/prisma/_config.py
=> feat(prisma): upgrade to v4.10.1

src/prisma/__init__.py
=> feat(package): release v0.8.1

src/prisma/cli/commands/version.py, tests/test_cli/test_version.py
=> feat(cli): add binary cache directory to `prisma py version`

databases/templates/schema.prisma.jinja2, src/prisma/generator/models.py
=> fix(generator): AST definitions for default arrays

README.md, docs/index.md, docs/reference/binaries.md, docs/reference/config.md, src/prisma/_config.py
=> feat(prisma): upgrade to v4.11.0

src/prisma/cli/prisma.py
closes #705
I haven't tested these changes yet.
=> fix(cli): ensure entrypoint only exists if npm install passes

src/prisma/__init__.py
=> feat(package): release v0.8.2

typesafety/mypy/test_mypy.yml
=> chore(tests): fix mypy typesafety tests

databases/tests/test_find_first_or_raise.py, databases/tests/test_find_unique_or_raise.py, docs/reference/operations.md, src/prisma/generator/templates/_utils.py.jinja, src/prisma/generator/templates/actions.py.jinja, src/prisma/generator/templates/builder.py.jinja, tests/test_builder.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[actions.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[builder.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[actions.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[builder.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
=> feat(client): add `find_unique_or_raise` & `find_first_or_raise`

src/prisma/generator/models.py, tests/test_generation/test_validation.py, tests/utils.py
=> feat(generator): improve error message for unsupported composite types

docs/contributing/contributing.md
=> chore(docs): minor improvements

README.md, databases/tests/test_errors.py, databases/tests/test_find_many.py, docs/index.md, docs/reference/binaries.md, docs/reference/config.md, src/prisma/__init__.py, src/prisma/_config.py, src/prisma/engine/utils.py, src/prisma/errors.py
=> feat(prisma): upgrade to v4.13.0

README.md, docs/index.md, docs/reference/binaries.md, docs/reference/config.md, src/prisma/_config.py
=> feat(prisma): upgrade to v4.14.0

README.md, docs/index.md, docs/reference/binaries.md, docs/reference/config.md, src/prisma/_config.py, tests/test_generation/test_validation.py
=> feat(prisma): upgrade to v4.15.0

docs/reference/operations.md
=> fix(docs): typo in operations.md

src/prisma/__init__.py
=> feat(package): release v0.9.0

src/prisma/generator/templates/engine/query.py.jinja, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[enginequery.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[enginequery.py].raw
=> fix(client): ensure engine protocol is properly set

docs/reference/troubleshooting.md
=> docs: add missing code block close tag

README.md, docs/getting_started/advanced.md, docs/getting_started/quickstart.md, docs/getting_started/type-safety.md, docs/index.md, docs/reference/troubleshooting.md, examples/discord-message-counter/bot.py, tests/Dockerfile
=> docs: polishes & typos

src/prisma/__init__.py
=> feat(package): release v0.9.1

docs/reference/type_checkers/pyright.md
=> docs: typos

src/prisma/generator/templates/client.py.jinja, tests/test_client.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
Asked for here: https://discord.com/channels/933860922039099444/933860923117043718/1135458731006632027
=> feat(client): add is_registered() method

src/prisma/__init__.py
=> feat(package): release v0.10.0

README.md, docs/index.md, docs/reference/binaries.md, docs/reference/config.md, src/prisma/_config.py
=> feat(prisma): upgrade to v5.4.2

databases/sync_tests/test_metrics.py, databases/templates/schema.prisma.jinja2, databases/tests/test_metrics.py, docs/reference/metrics.md, mkdocs.yml, src/prisma/__init__.py, src/prisma/_metrics.py, src/prisma/generator/models.py, src/prisma/generator/templates/client.py.jinja, src/prisma/generator/templates/engine/abstract.py.jinja, src/prisma/generator/templates/engine/http.py.jinja, src/prisma/generator/templates/engine/query.py.jinja, src/prisma/generator/templates/types.py.jinja, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[engineabstract.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[enginehttp.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[enginequery.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[types.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[engineabstract.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[enginehttp.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[enginequery.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[types.py].raw
=> feat(client): add support for metrics

src/prisma/__init__.py
=> feat(package): release v0.11.0

README.md, docs/index.md, docs/reference/binaries.md, docs/reference/config.md, src/prisma/_compat.py, src/prisma/_config.py
=> feat(prisma): upgrade to v5.6.0

.github/workflows/test.yml
=> ci: run database tests under multiple python versions

.github/workflows/test.yml, databases/tests/test_enum.py, requirements/base.txt, src/prisma/_compat.py, src/prisma/generator/templates/enums.py.jinja, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[enums.py].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[enums.py].raw
=> fix(enums): ensure consistent enum format in 3.11+

README.md, docs/index.md, docs/reference/binaries.md, docs/reference/config.md, src/prisma/_config.py
=> feat(prisma): upgrade to v5.7.0

README.md, docs/index.md, docs/reference/binaries.md, docs/reference/config.md, src/prisma/_config.py
=> feat(prisma): upgrade to v5.7.1

databases/main.py, examples/flask-url-shortener/app.py, pipelines/lint.nox.py, pyproject.toml, src/prisma/__init__.py, src/prisma/_compat.py, src/prisma/cli/_node.py, src/prisma/cli/utils.py, src/prisma/generator/jsonrpc.py, src/prisma/generator/utils.py, src/prisma/mypy.py, src/prisma/utils.py, src/prisma_cleanup/_cleanup.py, tests/test_generation/test_generator.py, tests/test_generation/test_partial_types.py, typesafety/pyright/include.py
=> chore(project): enable ruff lint rules

README.md, docs/index.md, docs/reference/binaries.md, docs/reference/config.md, src/prisma/_config.py
=> feat(prisma): upgrade to v5.8.0

src/prisma/__init__.py
=> feat(package): release v0.12.0

databases/tests/test_create.py
=> chore(tests): bump time threshold for flaky test

.github/renovate.json
It's considerably easier to incrementally update deps one by one
=> chore(renovate): remove dev group

src/prisma/_compat.py, src/prisma/generator/models.py, src/prisma/generator/templates/client.py.jinja, tests/data/schema.prisma
should fix #858
not sure how our tests didn't catch this... looking into that as well
=> fix(generator): remove use of deprecated pydantic methods

src/prisma/generator/utils.py, tests/test_generation/test_utils.py
Cherry-picked from #877 and updated slightly.
=> chore(internal): add change case util functions 

README.md, docs/index.md, docs/reference/binaries.md, docs/reference/config.md, src/prisma/_config.py
=> feat(prisma): upgrade to v5.14.0

databases/sync_tests/test_transactions.py, databases/tests/test_transactions.py, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[schema.prisma].raw, tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[schema.prisma].raw, tests/test_generation/exhaustive/test_exhaustive.py
=> feat(tests): include the package schema file in snapshot tests

.github/workflows/test.yml, .gitignore, Makefile, integrations/prisma-schema-folder/README.md, integrations/prisma-schema-folder/conftest.py, integrations/prisma-schema-folder/prisma/schema/main.prisma, integrations/prisma-schema-folder/prisma/schema/user.prisma, integrations/prisma-schema-folder/test_main.py, pipelines/integrations.nox.py, pipelines/requirements/integration-prisma-schema-folder.txt, pytest.ini, src/prisma/generator/generator.py, tests/integrations/recursive-types/schema.prisma
=> fix(generator): support prisma schema folder preview feature

src/prisma/generator/jsonrpc.py
Would make debugging https://github.com/RobertCraigie/prisma-client-py/issues/984 much easier
=> chore(jsonrpc): add debug logs for line parsing

src/prisma/__init__.py
=> feat(package): release v0.15.0

docs/getting_started/advanced.md
There is a link to the Prisma Client Go documentation, but it no longer works because the path to the other document has changed.
=> docs: update the link in advanced.md
