- src/prisma/generator/templates/actions.py.jinja
- src/prisma/generator/templates/types.py.jinja
- tests/test_count.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr
- typesafety/mypy/test_mypy.yml
- typesafety/pyright/count.py
closes #13 
```py
count = await client.user.count(
select={
'email': True,
},
)
```
> feat(client): add support for selecting fields to count

- requirements/base.txt
- src/prisma/_types.py
- src/prisma/generator/templates/_header.py.jinja
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr
fixes #114 
On Python 3.9.0 and Python 3.9.1, `typing.TypedDict` does not correctly hold the `__required_keys__` and `__optional_keys__` attributes, the fix (https://github.com/python/cpython/pull/22736) for this issue was merged on 10/12/2020 and Python 3.9.1 was released on 8/12/2020, as such, the minimum Python version that does not require the use of `typing-extensions` is Python 3.9.2
However, writing our imports this way breaks mypy, reporting 1651 errors :)
> fix(validator): always require typing-extensions

- src/prisma/generator/models.py
For some reason Prisma is sending a generator with no provider value, we actually don't use this anywhere so it's safe to just make it `Optional`.
closes #120
> fix(generator): make the generator provider optional

- src/prisma/generator/templates/fields.py.jinja
- tests/test_fields.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr
Support for:
```py
from prisma import Base64
assert Base64.encode(b'foo') == Base64.encode(b'foo')
```
> feat(fields): add support for comparing Bytes field instances

- src/prisma/generator/templates/fields.py.jinja
- tests/integrations/postgresql/tests/test_arrays.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr
- tests/test_types/test_bytes.py
This shouldn't really be used by consumers of this library, however
for correctness sake we should support this
> feat(models): support manually constructing models with bytes fields

- docs/contributing/contributing.md
- pytest.ini
- src/prisma/testing.py
- tests/conftest.py
- tests/test_misc.py
- tests/test_models.py
- tests/test_testing.py
this is done to reduce redundant database cleanup
> refactor(tests): tests must be explicitly marked for model-based access

- src/prisma/_compat.py
- src/prisma/_types.py
- src/prisma/generator/models.py
- src/prisma/generator/schema.py
Comment copy pasted for context:
```
```
> chore(types): fix type completeness errors

- src/prisma/generator/models.py
- src/prisma/generator/templates/client.py.jinja
- src/prisma/utils.py
- tests/data/schema.prisma
- tests/integrations/postgresql/schema.prisma
- tests/test_client.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive.ambr
we currently only support the binary option but this will be useful in the future
> feat(client): expose client engine type

- codecov.yml
This is an attempt to stop codecov from prematurely failing a commit
> chore(ci): increase codecov threshold

- .github/workflows/test.yml
- README.md
- docs/contributing/contributing.md
- docs/getting_started/setup.md
- docs/index.md
- docs/src_examples/async/index.py
- setup.py
- src/prisma/_compat.py
- src/prisma/_types.py
- src/prisma/generator/generator.py
- tests/integrations/custom-generator/generator.py
- tests/test_generation/test_generator.py
- tox.ini
closes #87 
Quite a few of our dependencies are dropping support for Python 3.6 in their latest releases and Python 3.6 reached it's EOL on the 23rd of December 2021
> chore(package): drop support for Python 3.6

- .github/workflows/test.yml
- docs/contributing/contributing.md
- pytest.ini
- tests/conftest.py
- tests/integrations/custom-generator/test.sh
- tests/integrations/postgresql/pyproject.toml
- tests/integrations/postgresql/pytest.ini
- tests/integrations/postgresql/requirements.txt
- tests/integrations/sync/test.sh
- tests/test_include.py
- tests/test_update.py
- tests/utils.py
- tox.ini
Bumps internal testing dependency `pytest-asyncio` from `v0.14.0` to `v0.17.0`, this requires async fixtures to be explicitly marked.
> chore(tests): update pytest-asyncio to v0.17.0

- .pylintrc
- requirements/base.txt
- src/prisma/_compat.py
- src/prisma/generator/generator.py
- src/prisma/generator/models.py
- src/prisma/generator/schema.py
- src/prisma/mypy.py
Make use of the standard library's `functools.cached_property` (and it's backport) on expensive to compute properties.
> feat(project): apply cached-property where applicable

- requirements/base.txt
- tox.ini
Remove `contextvars` from requirements as it is no longer used due to dropping support for Python 3.6
> chore(deps): remove redundant backport dependency

- .github/workflows/scorecards-analysis.yml
Make use of Github's Security features: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
> feat(ci): Add OpenSSF scorecards

- setup.py
The package metadata now lists the minimum python version required as Python 3.7. It was previously just Python 3.
> chore(package): fix python version metadata

- tests/test_engine.py
Fixes local broken tests due to missing event loop. This could happen if you ran `test_engine.py` by itself as it would unconditionally set the event loop to None. This has been changed to only touch the event loop if one is already running.
> chore(tests): fix local no event loop error

- src/prisma/generator/schema.py
- src/prisma/generator/templates/types.py.jinja
- tests/test_find_many.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[types.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[types.py].raw
- typesafety/pyright/ordering.py
Improves the `order` type to signify that only one field can be present at any given time.
> feat(types): improve order by type safety

- tox.ini
Pin `pytest` to `6.2.4` due to incompatibilities with `7.0.0`.
> chore(typesafety/pyright): fix pytest warning

- docs/reference/client.md
- src/prisma/generator/templates/types.py.jinja
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[types.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[types.py].raw
This supports removing the HTTP timeout from the client.
> feat(client): support removing the http timeout

- .gitignore
- src/prisma/_async_http.py
- src/prisma/_sync_http.py
- src/prisma/binaries/utils.py
- src/prisma/cli/cli.py
- src/prisma/engine/errors.py
- src/prisma/engine/utils.py
- src/prisma/generator/generator.py
- src/prisma/generator/utils.py
- src/prisma/http.py
- src/prisma/http_abstract.py
- tests/test_generation/test_generator.py
- tests/test_http.py
The previous `http.py` behaviour where it was overridden during generation was confusing for new contributors.
This was also prone to bugs as we only run type checks post-generation where the http client would be an async client, however it could also have been a sync client which we would not check for.
> refactor(package): make http.py only available post-generation

- src/prisma/_async_http.py
- src/prisma/_sync_http.py
- src/prisma/generator/templates/actions.py.jinja
- src/prisma/generator/templates/builder.py.jinja
- src/prisma/generator/templates/client.py.jinja
- src/prisma/generator/templates/fields.py.jinja
- src/prisma/http_abstract.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[actions.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[builder.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[fields.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[actions.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[builder.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[fields.py].raw
- tox.ini
Closes #299 
Adds `__slots__` to:
- `client.Prisma`
- `actions.*Actions`
- `http_abstract.HTTP` (+ sync and async subclasses)
- `http_abstract.Response` (+ sync and async subclasses)
- `QueryBuilder` + `Node` and its subclasses
- the `Base64` field type
I haven't added `__slots__` to models yet, but I would like to. The issue mentions that you're not sure about it, but I frankly can't see any problems it could cause. The `pydantic.BaseModel` superclass is slotted, and should someone need to subclass a model (though why would they?), slots on the model itself shouldn't cause any trouble.
> feat(package): add __slots__

- docs/reference/operations.md
- src/prisma/generator/templates/types.py.jinja
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[types.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[types.py].raw
- tests/test_types/test_bytes.py
Closes #156 
Adds support for filtering `Bytes` fields by `in`/`not_in`.
> feat(types): add support for in/not_in for Bytes

- src/prisma/generator/templates/client.py.jinja
- tests/test_client.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
We forgot to actually continue to export the old `Client` alias when we changed it to `Prisma`
> fix(client): export Client alias

- README.md
- docs/index.md
- docs/reference/binaries.md
- src/prisma/binaries/constants.py
Upgrade internal Prisma binaries to `v3.10.0`.
closes #326
> feat(prisma): upgrade to prisma@3.10.0

- src/prisma/binaries/constants.py
- src/prisma/generator/models.py
- src/prisma/generator/templates/client.py.jinja
- src/prisma/generator/templates/fields.py.jinja
- src/prisma/generator/templates/models.py.jinja
- src/prisma/generator/templates/types.py.jinja
- src/prisma/http_abstract.py
- src/prisma/utils.py
- src/prisma/validator.py
- tests/integrations/conftest.py
- tests/test_builder.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[fields.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[models.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[types.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[fields.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[models.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[types.py].raw
- tests/test_generation/test_generator.py
- tests/test_generation/test_models.py
- tests/test_group_by.py
- tests/test_http.py
- tests/test_include.py
- tests/test_models.py
- tests/test_types/test_bigint.py
- tests/test_types/test_float.py
- tests/test_types/test_int.py
- tests/test_update.py
- tox.ini
These comments disabled the diagnostic for the entire module when I only intended for them to be disabled on an individual line. This PR fixes that and removes some redundant comments
> chore(lint): fix invalid pyright configuration comments

- src/prisma/generator/templates/client.py.jinja
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
Export `Batch` so it can be used like so:
```py
from prisma import Batch, Prisma
prisma = Prisma()
async with Batch(prisma) as batcher:
...
```
> feat(client): export query batcher for alternative API style

- src/prisma/_types.py
- src/prisma/cli/commands/dev.py
- src/prisma/utils.py
- tox.ini
- Add TypeGuard to `is_coroutine`
- Add TypeVar to `async_run`
- Return `object` instead of `Any` for `maybe_async_run`
> feat(typings): more accurate types for internal utility functions

- src/prisma/engine/utils.py
- src/prisma/errors.py
- tests/test_errors.py
Add `ForeignKeyViolationError` to the client error map.
Closes https://github.com/RobertCraigie/prisma-client-py/issues/351
> feat(client): add ForeignKeyViolationError

- README.md
- docs/getting_started/setup.md
- docs/index.md
- docs/src_examples/advanced.schema.prisma
- docs/src_examples/async/index.schema.prisma
- docs/src_examples/basic.schema.prisma
- docs/src_examples/sync/index.schema.prisma
- examples/discord-message-counter/schema.prisma
- examples/flask-url-shortener/schema.prisma
- examples/kivy-basic/schema.prisma
- src/prisma/generator/models.py
- tests/test_generation/test_models.py
Warn users when they don't set recursive type depth in the prism schema. The warning should tell users that they can set it to -1 for use with Pyright.
Closes https://github.com/RobertCraigie/prisma-client-py/issues/252
> feat(cli): warn when recursive type depth not set in prism schema

- src/prisma/testing.py
- tests/test_testing.py
As suggested in https://github.com/RobertCraigie/prisma-client-py/issues/243, this adds a `unregister_client` function that unregisters/deregisters the prisma client.
Closes https://github.com/RobertCraigie/prisma-client-py/issues/243
> feat(tests): add support for unregistering a client

- src/prisma/generator/models.py
- src/prisma/generator/templates/client.py.jinja
- tests/test_client.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
- tests/test_generation/exhaustive/test_exhaustive.py
- tests/test_misc.py
closes #400 
closes #409
This PR overrides the default SQLite URL to use a path relative to the Prisma Schema file instead of the working directory. This is a breaking change but is required in order to maintain consistency between the CLI and the Client.
This PR also exports a new constant, `SCHEMA_PATH` which points to the location of the schema file used to generate the client.
```py
from prisma import SCHEMA_PATH
print(SCHEMA_PATH)  # Path('/absolute/path/prisma/schema.prisma')
```
> fix(client): override the default SQLite relative file path

- src/prisma/generator/templates/models.py.jinja
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[models.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[models.py].raw
- tests/test_generation/test_partial_types.py
Closes #436 
This also enforces that `include` and `exclude_relational_fields=True` are mutually exclusive.
> fix(partials): support combining exclude and exclude_relational_fields

- requirements/base.txt
- src/prisma/__init__.py
- src/prisma/_config.py
- src/prisma/binaries/binaries.py
- src/prisma/binaries/binary.py
- src/prisma/binaries/constants.py
- src/prisma/binaries/engine.py
- src/prisma/cli/commands/version.py
- src/prisma/engine/utils.py
- src/prisma/generator/models.py
- tests/test_cli/test_fetch.py
- tests/test_config.py
- tests/test_engine.py
- tests/utils.py
You can now configure certain options using an entry in your `pyproject.toml` file instead of having to set environment variables, e.g.
```toml
[tool.prisma]
binary_cache_dir = '.binaries'
```
It should be noted that you can still use environment variables if you so desire, e.g.
```sh
PRISMA_BINARY_CACHE_DIR=".binaries"
```
This will be useful as a workaround for #413 until the default behaviour is changed.
> feat(project): add support for configuration through pyproject.toml

- README.md
- docs/index.md
Hello.
In example `schema.prisma` file User has email required field. But in example with python client specified only name. If run it example than an error will occur:
```prisma.errors.MissingRequiredValueError: Failed to validate the query: `Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOneUser.data.UserCreateInput.email`: A value is required but not set., Query parsing/validation error at `Mutation.createOneUser.data.UserUncheckedCreateInput.email`: A value is required but not set.]` at `Mutation.createOneUser.data```
> docs(readme): add missing required email in insert examples

- .github/workflows/test.yml
- requirements/dev.txt
- tox.ini
See https://github.com/grantjenks/blue/issues/78 and #451.
> chore(deps): fix errors relating to recent releases

- docs/getting_started/advanced.md
The examples to search comments were not working as expected, so I fixed them
I fixed examples to read comments in the `getting started` documentation
> docs(getting-started): Fix comment example

- .pre-commit-config.yaml
A release of `flake8` broke `blue` so we need to bump `blue` to the latest version.
> fix(pre-commit): bump blue hook to `v0.9.1`

- .github/workflows/test.yml
- tests/integrations/custom-generator/generator.py
- tests/integrations/custom-generator/pyproject.toml
- tests/integrations/custom-generator/requirements.txt
Forgot to make this change when I added support for Python  3.11 earlier.
> feat(ci): run Python 3.11 on CI

- setup.py
Changes `setup.py` to always open files in UTF-8 encoding to avoid weird encoding errors when installing the package.
N/A
> fix(package): force utf-8 in setup

- src/prisma/generator/templates/engine/query.py.jinja
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[enginequery.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[enginequery.py].raw
The previous implicit cast to `str` may break on some systems.
> fix(engine): explicitly cast `Path` to a string for env variables

- src/prisma/_compat.py
- src/prisma/generator/templates/client.py.jinja
- tests/test_client.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
I adjusted how SQLite URL is trimming "file:" and "sqlite:" prefixes in the beginning of connection string.
This was causing incorrect trimming when database file name starts with any character from those prefixes.
Example: "sqlite:teh.db" has been trimmed to "h.db".
The nature of lstrip method trims characters left to right while next symbol is found in the set of given characters.
Workaround: use relative path syntax like "sqlite:./teh.db".
> fix(client): prevent the deletion of sqlite dbname

- src/prisma/generator/generator.py
- tests/test_generation/test_generator.py
> fix(generator): do not copy schema file if generating to the current dir

- .dockerignore
- .github/workflows/test.yml
- Dockerfile
- Makefile
- docs/contributing/contributing.md
- tests/Dockerfile
This PR adds a basic docker build setup that exercises the `prisma` CLI, building for multiple platforms in Docker via `--platform=linux/amd64,linux=arm64`
Additionally, it starts to exercise the build against multiple [Linux distributions for Python](https://hub.docker.com/_/python), starting with a basic support matrix for Debian Buster and Alpine (latest).
The scope is **not to publish** any sort of official image, but rather since GH Actions does not support an ARM CPU runner we can emulate how a build would have performed via the QEMU emulation of docker.
Relates to #454
Relates to #461
Relates to #507 
CI results for this running off of my fork can be found here: https://github.com/jacobdr/prisma-client-py/pull/1
By submitting this pull request, I confirm that you can use, modify, …
> feat(ci): Add initial test case for a Docker build in CI for multi-platform builds

- src/prisma/mypy.py
`mypy` command gives the following error and I found https://github.com/python/mypy/pull/13254 and https://github.com/python/mypy/issues/12237 .
So, I removed it.
> chore(project): Removed UnicodeExpr as it is no longer supported

- .github/dependabot.yml
I've noticed that dependabot isn't opening PRs for any of our test dependencies. As per https://github.com/dependabot/dependabot-core/issues/2824 it looks like we have to explicitly add it as a separate entry in the config file.
> chore(dependabot): add pipelines requirements to config

- .github/workflows/test.yml
- tests/Dockerfile
- tests/windows.Dockerfile
* Fix issue with testing alpine-based docker in CI. However, since the Go Prisma CLI does not work on Alpine, I had to disable the test as it fails
* Start to set up PKI machinery for Windows to deal with nodeenv downloads -- unclear why we need this but starts to put the infrasctructure there inc ase we need it
* Implement better caching to speed up docker build times -- but does not work on Windows since we don't have buildx so we won't see an improvement there
In the initial PR (#521) where I added Docker-based CI I forgot to pass through the Docker build arg with `=` -- so the variation we wanted to test on Alpine was not working as expected. This PR fixes that, so that the `OS_DISTRO` is properly populated
By submitting this pull request, I confirm that you can use, modify, copy and …
> fix(ci): Docker build issues

- .github/workflows/docs.yml
- mkdocs.yml
This PR adds a new `docs` action that simply builds the documentation to ensure there are no warnings generated. This will be useful for testing Dependabot PRs that update a documentation dependency.
> feat(ci): add action to test documentation building

- tests/test_generation/exhaustive/test_exhaustive.py
This PR disables the creation of diffs for our snapshot tests on the generated client code. This is because it can take a *long* time to generate this diff in CI and we don't really care what the actual diff is, we just need to know that there is a difference.
https://github.com/tophat/syrupy/issues/581
> chore(tests): disable snapshot diffs

- src/prisma/generator/models.py
- tests/test_generation/test_validation.py
> fix(generator): validate model name is not a reserved keyword

- src/prisma/_config.py
- src/prisma/_proxy.py
- tests/test_proxy.py
This PR improves our internal proxy type:
- adds an `__as_proxied__` method that performs type casting for you.
- adds unit tests
> feat(proxy): add helper method for casting types and tests

- .coveragerc
- .github/workflows/test.yml
- databases/main.py
- pipelines/coverage.nox.py
This PR includes the generated `htmlcov` report in the `static/coverage` branch and improves coverage in some small areas.
> feat(coverage): store coverage reports too

- pipelines/coverage.nox.py
- src/prisma/generator/templates/models.py.jinja
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[models.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[partials.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[models.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[partials.py].raw
- tests/test_generation/exhaustive/async.schema.prisma
- tests/test_generation/exhaustive/partials.py
- tests/test_generation/exhaustive/sync.schema.prisma
Under certain conditions the generation of a partial type may use an incorrect type if another partial type was then generated that modified a relational type.
For example given this partial type generator:
```py
from prisma.models import Post, User
Post.create_partial('PostWithAuthor', include={'id', 'title', 'author'})
User.create_partial('UserOnlyName', include={'name'})
Post.create_partial(
'PostWithCustomAuthor',
include={'id', 'title', 'author'},
relations={
'author': 'UserOnlyName',
},
)
User.create_partial('UserWithPosts', include={'name', 'posts'})
Post.create_partial(
'PostWithNestedRelations',
include={'id', 'title', 'author'},
relations={
'author': 'UserWithPosts',
},
)
```
Would generate this partial type:
```py
class PostWithAuthor(BaseModel):
title: _str
author: …
```
> fix(partials): remove data leak when modifying relational types

- .github/workflows/test.yml
- databases/main.py
- databases/tests/test_create_many.py
This PR adds inverse tests to our database testing suite to ensure that unsupported features are actually unsupported and trying to use them will result in either a Prisma Schema validation fail or type checking to fail & runtime tests to fail.
This currently just checks that running these commands fail but in the future we'll probably want more fine grained checks to ensure that the exact right things are failing.
closes #561
> feat(databases): add inverse tests for unsupported features

- .github/workflows/test.yml
- databases/constants.py
- databases/tests/arrays/push/test_bigint.py
- databases/tests/arrays/push/test_bool.py
- databases/tests/arrays/push/test_bytes.py
- databases/tests/arrays/push/test_datetime.py
- databases/tests/arrays/push/test_decimal.py
- databases/tests/arrays/push/test_enum.py
- databases/tests/arrays/push/test_float.py
- databases/tests/arrays/push/test_int.py
- databases/tests/arrays/push/test_json.py
- databases/tests/arrays/push/test_string.py
- databases/tests/arrays/test_bigint.py
- databases/tests/arrays/test_bool.py
- databases/tests/arrays/test_bytes.py
- databases/tests/arrays/test_datetime.py
- databases/tests/arrays/test_decimal.py
- databases/tests/arrays/test_enum.py
- databases/tests/arrays/test_float.py
- databases/tests/arrays/test_int.py
- databases/tests/arrays/test_json.py
- databases/tests/arrays/test_string.py
- databases/tests/test_update.py
- databases/utils.py
- src/prisma/generator/templates/types.py.jinja
This PR:
- Adds CockroachDB back to the list of tested databases in CI
- Disables generating the array `push` operation for CockroachDB
- Adds CockroachDB to the list of whitelisted databases for case sensitivity
closes #636
> feat(client): add support for CockroachDB

- databases/tests/test_find_first.py
- databases/tests/test_find_many.py
- docs/reference/operations.md
- src/prisma/generator/templates/actions.py.jinja
- src/prisma/generator/templates/types.py.jinja
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[actions.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[types.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[actions.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[types.py].raw
This PR adds support for the `distinct` filter to `find_many()` and `find_first()` queries.
closes #654
> feat(client): add distinct filter to find_first and find_many

- .github/workflows/test.yml
- typesafety/mypy/test_mypy.yml
Re-enable the Mypy typesafety tests in CI.
> feat(ci): test mypy typesafety

- docs/reference/limitations.md
- src/prisma/errors.py
- src/prisma/generator/templates/actions.py.jinja
- src/prisma/generator/templates/client.py.jinja
- src/prisma/generator/templates/models.py.jinja
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[actions.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[models.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[actions.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[models.py].raw
- tests/test_models.py
This restriction is no longer needed as mypy has fixed a lot of performance issues and this change no longer results in a ridiculous runtime for mypy.
> feat(models): remove non-recursive types subclass restriction

- Makefile
- databases/requirements.txt
closes #579, all internal dependencies were already consolidated into our `lint` workflow anyway.
This PR makes the following changes to `make bootsrap`
- ensure it installs all dependencies
- remove pre-commit hook
- I no longer think this is a good idea to "force" onto contributors
- It can be annoying and we have auto fixes in CI anyway
> feat(contributing): improve make bootstrap

- .envrc
- .gitignore
Adds a `.envrc` file which just sources `.envrc.local` for now.
I plan on using this to make it easier to run database tests locally.
> chore(contrib): add .envrc for future expansion

- src/prisma/__init__.py
- src/prisma/_types.py
- src/prisma/generator/templates/_utils.py.jinja
- src/prisma/generator/templates/actions.py.jinja
- src/prisma/generator/templates/builder.py.jinja
- src/prisma/generator/templates/client.py.jinja
- tests/test_builder.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[actions.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[builder.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[actions.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[builder.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
This PR refactors the internal `QueryBuilder` to accept the python method name, e.g. `find_unique`, instead of the internal GraphQL operation + method name.
This makes the middleware implementation easier.
> refactor(builder): work with python method name instead of graphql name

- src/prisma/engine/utils.py
- tests/test_engine.py
The error message was misleading, they also might not be resolved because they could not be executed.
> feat(engine): improve error message for missing binary

- requirements/base.txt
> chore(deps): pin pydantic < 2

- databases/sync_tests/test_transactions.py
- databases/tests/test_transactions.py
- src/prisma/_constants.py
- src/prisma/generator/templates/client.py.jinja
- src/prisma/generator/templates/engine/abstract.py.jinja
- src/prisma/generator/templates/engine/http.py.jinja
- src/prisma/generator/templates/engine/query.py.jinja
- tests/test_client.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[engineabstract.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[enginehttp.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[enginequery.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[engineabstract.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[enginehttp.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[enginequery.py].raw
- tests/test_typing_warnings.py
Updated types and added respective warnings with tests:
* Connect timeout: `int` -> `Union[int, timedelta]`
* Disconnect timeout: `float` -> `Union[float, timedelta]`
* Transaction max wait: `int` -> `Union[int, timedelta]`
* Transaction timeout: `int` -> `Union[int, timedelta]`
Closes https://github.com/RobertCraigie/prisma-client-py/issues/167.
> feat(client): time params accept `datetime.timedelta`

- databases/sync_tests/test_transactions.py
- databases/tests/test_transactions.py
- docs/reference/transactions.md
- src/prisma/_constants.py
- src/prisma/generator/templates/client.py.jinja
- src/prisma/generator/templates/engine/abstract.py.jinja
- src/prisma/generator/templates/engine/http.py.jinja
- src/prisma/generator/templates/engine/query.py.jinja
- tests/test_client.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[engineabstract.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[enginehttp.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[enginequery.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[client.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[engineabstract.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[enginehttp.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[enginequery.py].raw
- tests/test_typing_warnings.py
Retry of #807 as I messed up merging.
> feat(client): accept datetime.timedelta instead of int

- src/prisma/cli/_node.py
> feat(cli): add error log if nodeenv fails

- docs/getting_started/quickstart.md
> docs: fix a broken link and typos

- src/prisma/generator/models.py
- src/prisma/generator/templates/actions.py.jinja
- src/prisma/generator/templates/client.py.jinja
Having a single source of truth for names makes them much more consistent and less error-prone.
> refactor(templates): rely on a constant for model instance names

- databases/main.py
- requirements/base.txt
Updated the minimum version of pydantic to `1.10.0`. Current version is set to `1.8.0` but it lacks some required typing extensions.
Run:
```
pip3 install pydantic==1.8.0 prisma
python3 -c 'import prisma'
```
Output:
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/ezorita/tmp/prisma-pydantic/lib/python3.8/site-packages/prisma/__init__.py", line 11, in <module>
from ._config import config as config
File "/home/ezorita/tmp/prisma-pydantic/lib/python3.8/site-packages/prisma/_config.py", line 12, in <module>
from ._compat import (
File "/home/ezorita/tmp/prisma-pydantic/lib/python3.8/site-packages/prisma/_compat.py", line 162, in <module>
from pydantic.typing import is_union as is_union
ImportError: cannot import name 'is_union' from 'pydantic.typing' …
```
> fix(requirements): set minimum pydantic version to 1.10.0

- pipelines/requirements/dev.txt
- src/prisma/_compat.py
- typesafety/pyright/schema.prisma
- typesafety/pyright/types/enum.py
This addresses an issue with typing where string enums generated by prisma are not compatible with str typing. This specifically fixes an issue where Pyright checks would fail since prisma StrEnum has type Enum, which is not valid as a str.
> fix(types): remove definition of StrEnum as Enum

- src/prisma/generator/models.py
- src/prisma/generator/schema.py
- src/prisma/generator/templates/types.py.jinja
> chore(internal): support rendering enum types from the DMMF

- src/prisma/cli/_node.py
- tests/test_node/test_node.py
Prisma bumped this so we need to as well: https://github.com/prisma/prisma/blob/main/package.json
> fix(node): bump minimum node version to v16

- src/prisma/generator/schema.py
- src/prisma/generator/templates/types.py.jinja
We shouldn't be overloading `subtypes` for unions as we may need to distinguish between `subtypes` and `variants`, e.g. each variant has the same shared parent class
> chore(internal): restructure PrismaUnion representation

- databases/sync_tests/test_create.py
- databases/tests/test_create.py
- src/prisma/_constants.py
- src/prisma/generator/templates/types.py.jinja
- tests/test_actions.py
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[types.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[types.py].raw
Adds connectOrCreate to support #754
Please let me know if I should make write tests (and where to put them). Thanks @RobertCraigie for your work on this great library!
> feat(client): add connect_or_create

- databases/sync_tests/types/raw_queries/test_bigint.py
- databases/sync_tests/types/raw_queries/test_decimal.py
- databases/tests/types/raw_queries/test_bigint.py
- databases/tests/types/raw_queries/test_decimal.py
- src/prisma/_raw_query.py
See https://github.com/RobertCraigie/prisma-client-py/issues/998 for the most part.
This PR goes in and makes the check mentioned in the above issue happen earlier.
Adding tests for JSON was not done due to technical difficulties I had when testing. Apparently, optional JSON fields can't accept a `None` value when being created, according to Prisma, despite the fact that I see it as [optional in the schema used](https://github.com/RobertCraigie/prisma-client-py/blob/f1ab3b183cbfaf2d0c7c0c9bce0aeec346236841/databases/templates/schema.prisma.jinja2#L87). I'll leave what errors I got below, though it may be just a me thing.
```python
record = await client.types.create({'json_obj': None})
```
```
prisma.errors.MissingRequiredValueError: Unable to match input value to any allowed input type …
```
> fix(raw queries): correct None handling for all fields

- databases/constants.py
- databases/sync_tests/test_full_text_search.py
- databases/templates/schema.prisma.jinja2
- databases/tests/test_full_text_search.py
- databases/utils.py
- docs/reference/operations.md
- src/prisma/generator/schema.py
- src/prisma/generator/templates/types.py.jinja
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async[types.py].raw
- tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_sync[types.py].raw
* #52
* Supports full text search in where clause for postgresql and mysql
* Supports relevance ordering - which requires tracking `active_provider` in `Model` context
> feat(client): Add support for full text search
